### ISSUE TITLE
v4.1.0: An error occurred when sending a notification using 'email' notifier.

### ISSUE THREAD

**Issue by steventwheeler** [smartinez87/exception_notification#270]
Hello, I just installed the 4.1.0 version of this gem and ran `rails g exception_notification:install` to generate the configuration.  I only modified the email_prefix, sender_address, and exception_recipients options. When an error occurs I see get the following stack trace in the console. Downgrading to version 4.0.1 resolved the problem for me. Please let me know if you need any additional information.

```
W, [2015-04-15T15:11:02.714919 #15004]  WARN -- : An error occurred when sending a notification using 'email' notifier. NoMethodError: private method `include' called for #<Class:0x000000084a3b68>
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionmailer-4.2.0/lib/action_mailer/base.rb:569:in `method_missing'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:20:in `block in extended'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:19:in `class_eval'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:19:in `extended'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:137:in `extend'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:137:in `block in mailer'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:136:in `tap'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:136:in `mailer'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:157:in `create_email'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:143:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier.rb:94:in `fire_notification'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier.rb:39:in `block in notify_exception'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier.rb:38:in `each'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notifier.rb:38:in `notify_exception'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notification/rack.rb:42:in `rescue in call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/exception_notification-4.1.0/lib/exception_notification/rack.rb:32:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/etag.rb:24:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/conditionalget.rb:25:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:378:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:73:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/web-console-2.1.2/lib/web_console/middleware.rb:37:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:22:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/lock.rb:17:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/lock.rb:17:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/content_length.rb:15:in `call'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
c:/Ruby200-x64/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
c:/Ruby200-x64/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
c:/Ruby200-x64/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
F, [2015-04-15T15:11:02.718920 #15004] FATAL -- :
```

**Comment by bollard** [comment]
I am seeing the same issue with Rails 4.1.10 and Exception Notification 4.1:

````
irb(main):003:0> ExceptionNotifier.notify_exception(Exception.new, {})
W, [2015-04-16T11:56:48.088202 #42258]  WARN -- : An error occurred when sending a notification using 'email' notifier. NoMethodError: private method `include' called for #<Class:0x00000007ffbc28>
/var/www/app/shared/bundle/ruby/1.9.1/gems/actionmailer-4.1.10/lib/action_mailer/base.rb:553:in `method_missing'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:20:in `block in extended'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:19:in `class_eval'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:19:in `extended'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:137:in `extend'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:137:in `block in mailer'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:136:in `tap'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:136:in `mailer'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:155:in `create_email'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier/email_notifier.rb:143:in `call'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier.rb:94:in `fire_notification'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier.rb:39:in `block in notify_exception'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier.rb:38:in `each'
/var/www/app/shared/bundle/ruby/1.9.1/gems/exception_notification-4.1.0/lib/exception_notifier.rb:38:in `notify_exception'
(irb):3:in `irb_binding'
````

**Comment by aleksanb** [comment]
I just had the same issue! Rails 3.2.21 on ruby 1.9.3.
Downgrading to 4.0.1 fixed this.

**Comment by kaorukobo** [comment]
+1
    rails (4.2.1)
    exception_notification (4.1.0)

**Comment by KaibinHuang** [comment]
+1
rails 3.2.10
jruby 1.7.6
exception_notification 4.1.0
4.0.1 did not have the issue.

**Comment by jameschao** [comment]
+1
rails (3.2.21)
exception_notification (4.1.0)
ruby 1.9.3p484
4.0.1 did not have the issue.

**Comment by jralonso** [comment]
+1
rails 3.2.21
ruby 2.0.0
exception_notification 4.1.0

Downgrade to 4.0.1 and now it is working as expected

**Comment by b2tech** [comment]
+1
rails 4.0.13
ruby 2.0.0p643
exception_notification 4.1.0

**Comment by micred** [comment]
+1
rails 4.1.9
jruby 1.7.19
exception_notification 4.1.0

**Comment by rohitn** [comment]
+1
rails 3.2.10
jruby 1.7.20
exception_notification 4.1.0
4.0.1 did not have this issue.

**Comment by rebelweb** [comment]
This did work for me as well.

My environment.
rails 4.1.10
jruby 1.7.18
exception_notification 4.1.0

E-Mails were sent after downgrading.

**Comment by Melancholic** [comment]
I encountered a problem too,

Rails 4.2.1
ruby 2.0.0p353
exception_notification 4.1.0.

Downgrading to 4.0.1 fixed this.

**Comment by joshco** [comment]
I'm seeing this with 4.1.0 too, 4.0.1 works

**Comment by danlherman** [comment]
+1, Same here 

Rails 4.1.10
ruby 2.2.2
exception_notification 4.1.0

**Comment by tonyxty** [comment]
+1
rails 4.2.1
ruby 2.0.0p481
exception_notification 4.1.0

**Comment by joshco** [comment]
Possible clue.
Are you attempting to monkey patch a class (eg Foo) by using a module and then calling Foo.include <module>

On an unrelated item, i was attempting to monkey patch String by using this method (which appears to be in wide use) and got that error.  I'm working with Rails 4.2 and ruby 2.0p481

It looks like you are doing this with a backtrace cleaner module at line:
https://github.com/smartinez87/exception_notification/blob/master/lib/exception_notifier/email_notifier.rb#L20

I am wondering if in recent ruby/rails core classes are preventing monkeypatching, perhaps looking forward to refinements

**Comment by o-r-r** [comment]
+1
Rails 4.2.1
ruby 2.2.0
exception_notification 4.1.0.

Downgrading to 4.0.1 fixed this.

**Comment by joshco** [comment]
Hey folks, based on my earlier comment, I tried a small fix on master to use an alternate way for monkeypatching.
It works for me.
If you have the inclination, please try my version at this pull request:
https://github.com/smartinez87/exception_notification/pull/278
https://github.com/smartinez87/exception_notification/pull/278/files

or grab master from my repo.
in your gemfile
````
gem 'exception_notification', github: 'joshco/exception_notification'
````
Let's see if it works for everyone and then maybe smartinez will take the change

**Comment by smartinez87** [comment]
hey @joshco, thanks for taking the time to look into this !
I've just merged your PR, and will release a new version with the fix.

**Comment by joshco** [comment]
Great. Happy to help.

**Comment by jsantos** [comment]
This is still happening to me on 4.1.1:

Ruby 2.0.0p645
Rails 4.1.12

Any clue?

**Comment by joshco** [comment]
Can you provide a stack trace?

**Comment by jsantos** [comment]
Sure:

```
SERVER_IP: W, [2015-07-01T04:44:37.116769 #1166]  WARN -- : An error occurred when sending a notification using 'email' notifier. EOFError: end of file reached
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/protocol.rb:153:in `read_nonblock'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/protocol.rb:153:in `rbuf_fill'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/smtp.rb:932:in `recv_response'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/smtp.rb:918:in `block in getok'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/smtp.rb:942:in `critical'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/smtp.rb:916:in `getok'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/smtp.rb:910:in `quit'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/smtp.rb:616:in `do_finish'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/smtp.rb:523:in `ensure in start'
/home/ubuntu/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/net/smtp.rb:523:in `start'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionmailer-4.1.12/lib/action_mailer/base.rb:527:in `block in deliver_mail'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.12/lib/active_support/notifications.rb:159:in `block in instrument'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.12/lib/active_support/notifications.rb:159:in `instrument'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionmailer-4.1.12/lib/action_mailer/base.rb:525:in `deliver_mail'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/exception_notification-4.1.1/lib/exception_notifier/email_notifier.rb:147:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/exception_notification-4.1.1/lib/exception_notifier.rb:94:in `fire_notification'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/exception_notification-4.1.1/lib/exception_notifier.rb:39:in `block in notify_exception'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/exception_notification-4.1.1/lib/exception_notifier.rb:38:in `each'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/exception_notification-4.1.1/lib/exception_notifier.rb:38:in `notify_exception'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/exception_notification-4.1.1/lib/exception_notification/rack.rb:42:in `rescue in call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/exception_notification-4.1.1/lib/exception_notification/rack.rb:32:in `call'
/home/ubuntu/fms/releases/20150701040045/config/initializers/log_before_timeout.rb:15:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/rack-cors-0.3.1/lib/rack/cors.rb:72:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/flash.rb:254:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `
SERVER_IP: call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/cookies.rb:562:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/activerecord-4.1.12/lib/active_record/query_cache.rb:36:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/railties-4.1.12/lib/rails/rack/logger.rb:38:in `call_app'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/railties-4.1.12/lib/rails/rack/logger.rb:20:in `block in call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.12/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.12/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.12/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/railties-4.1.12/lib/rails/rack/logger.rb:20:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.12/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/sentry-raven-0.8.0/lib/raven/rack.rb:47:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/railties-4.1.12/lib/rails/engine.rb:514:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/railties-4.1.12/lib/rails/application.rb:144:in `call'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `load'
/home/ubuntu/fms/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `<main>'
```

**Comment by joshco** [comment]
Can you also provide the actual exception line that shows what exception and message occured?

**Comment by joshco** [comment]
Oh sorry, that's at the top.  This is a different error than the one identified in this issue, which is
> NoMethodError: private method `include' called for #<Class:0x00000007ffbc28>

Looks like you are experiencing a network issue.  Are your SMTP server settings correctly configured and is that server up, running and accepting connections?

**Comment by jsantos** [comment]
Oh, I haven't noticed that.

Yes, I guess the best explanation for this would be network issues on my end. Thanks for the heads-up!

**Comment by roma86** [comment]
Has same error with ruby 2.0.0, rails 4.2.3

reinstalling gem from ```gem 'exception_notification', github: 'joshco/exception_notification'``` fixed it.

Thank you, @joshco
